{{- if .Values.ingress.enabled -}}
{{- $fullName := include "api.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              {{- if $.Values.varnish.enabled }}
              service:
                name: {{ $fullName }}-varnish
                port:
                    number: {{ $.Values.varnish.service.port }}
              {{- else }}
              service:
                name: {{ $fullName }}-php
                port:
                    number: {{ $.Values.php.service.port }}
              {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
