apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
  {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.php.databaseUrl | b64enc | quote }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-token: {{ .Values.php.mercure.jwtToken | b64enc | quote }}
  blackfire-client-token: {{ .Values.php.blackfire.token | b64enc | quote }}
  blackfire-server-token: {{ .Values.blackfire.server.token | b64enc | quote }}
  jwt-secret: {{ .Values.php.jwt.secret | b64enc | quote }}
  jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  api-secret-token: {{ .Values.php.apiSecretToken | b64enc | quote }}
  mailer-dsn: {{ .Values.php.mailer.dsn | b64enc | quote }}
