{{- if .Values.varnish.enabled -}}
{{- $name := "varnish" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
{{- $fullName := include "api.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "api.labels" $data | nindent 4 }}
  annotations:
    {{- include "api.annotations" $data | nindent 4 }}
spec:
  replicas: {{ .Values.varnish.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" $data | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" $data | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- include "api.annotations" $data | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ $name }}
          image: "{{ .Values.varnish.image.repository }}:{{ .Values.varnish.image.tag }}"
          imagePullPolicy: {{ .Values.varnish.image.pullPolicy }}
          env:
          - name: UPSTREAM
            value: "{{ $fullName }}-php"
          - name: UPSTREAM_PORT
            value: "{{ .Values.php.service.port }}"
          - name: PHP_SERVICE
            value: "{{ $fullName }}-php"
          - name: CORS_ALLOW_ORIGIN
            valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}
                  key: cors-allow-origin
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-Kubernetes-Liveness
                  value: {{ $name }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-Kubernetes-Liveness
                  value: {{ $name }}
          resources:
{{ toYaml .Values.varnish.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
