## This has been modified from the API Platform template implementation
## More specifically from https://github.com/dunglas/demo-vulcain-api-platform
version: '3.8'

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/nginx}
      - ${PHP_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/php}
      - ${VARNISH_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/varnish}
  - &app-cache-from
    cache_from:
      - ${APP_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/app}

services:
  php:
    build:
      context: ./api
      target: cwa_php
      <<: *api-cache-from
    image: ${PHP_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/php}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - db
      - dev-tls
    environment:
      BLACKFIRE_CLIENT_ID: ~
      BLACKFIRE_CLIENT_TOKEN: ~
      # TODO: Remove environment variable once recipe is added to recipes-contrib repository
      SYMFONY_ENDPOINT: ~
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/_docker/php/conf.d/cwa.dev.ini:/usr/local/etc/php/cwa.dev.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
      - dev-certs:/certs:ro,nocopy

  api:
    build:
      context: ./api
      target: cwa_nginx
      <<: *api-cache-from
    image: ${NGINX_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/nginx}
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - target: 80
        published: 8080
        protocol: tcp

  cache-proxy:
    build:
      context: ./api
      target: cwa_varnish
      <<: *api-cache-from
    image: ${VARNISH_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/varnish}
    restart: always
    environment:
      UPSTREAM: api
      UPSTREAM_PORT: 80
      PHP_SERVICE: php
    depends_on:
      - api
    tmpfs:
      - /usr/local/var/varnish:exec
    volumes:
      - ./api/_docker/varnish/conf/default.vcl:/tmp/varnish/conf/default.vcl:rw

  vulcain:
    image: dunglas/vulcain
    environment:
      - CERT_FILE=/certs/localhost.crt
      - KEY_FILE=/certs/localhost.key
      - UPSTREAM=http://cache-proxy:8080
    depends_on:
      - cache-proxy
      - dev-tls
    volumes:
      - dev-certs:/certs:ro
    ports:
      - target: 443
        published: 8443
        protocol: tcp

  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_MULTIPLE_DATABASES=api,api_test
      - POSTGRES_USER=api-platform
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - ./api/_docker/postgres-init-scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data:rw,delegated
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mercure:
    image: dunglas/mercure
    environment:
      - ALLOW_ANONYMOUS=1
      - CERT_FILE=/certs/localhost.crt
      - CORS_ALLOWED_ORIGINS=*
      - DEMO=1
      - JWT_KEY=!ChangeMe!
      - KEY_FILE=/certs/localhost.key
      - PUBLISH_ALLOWED_ORIGINS=https://localhost:1337 # required for publishing from the demo page
    depends_on:
      - dev-tls
    volumes:
      - dev-certs:/certs:ro
    ports:
      - target: 443
        published: 1337
        protocol: tcp

  dev-tls:
    build:
      context: ./docker/dev-tls
    volumes:
      - dev-certs:/certs:rw
    ports:
      - target: 80
        published: 80
        protocol: tcp

  blackfire:
    image: blackfire/blackfire
    ports: ["8707"]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~
      # BLACKFIRE_LOG_LEVEL: 4

  app:
    build:
      context: ./app
      target: cwa_app
      <<: *app-cache-from
    image: ${APP_IMAGE:-registry.gitlab.com/silverback-web-apps/cwa/app}
    depends_on:
      - dev-tls
    volumes:
      - ./app:/usr/src/app:rw,cached
      - dev-certs:/certs:ro
    env_file:
      - ./app/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - target: 3000
        published: 443
        protocol: tcp
        
  admin:
    build:
      context: ./admin
      target: api_platform_admin_development
      cache_from:
        - ${ADMIN_IMAGE:-quay.io/api-platform/admin}
    image: ${ADMIN_IMAGE:-quay.io/api-platform/admin}
    depends_on:
      - dev-tls
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - dev-certs:/usr/src/admin/node_modules/webpack-dev-server/ssl:ro
    ports:
      - target: 3000
        published: 444
        protocol: tcp
    env_file:
      - ./admin/.env.local

  smtp_relay:
    image: namshi/smtp

volumes:
  db-data: {}
  dev-certs: {}
